### ISSUE TITLE
[TODO] List before making this repo public

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ethz-asl/reinmav-gym#19]
I have created a TODO list of the things we need to resolve before the release

- [x] Add `license.txt` for the repo
- [ ] ~~Basic usage documentation on [`readthedocs'](https://reinmav-gym-docs.readthedocs.io/en/latest/index.html)~~
- [x] baseline interface from a single `run.py` file
- [ ] Train network and save pretrained network for all environments
- [x] resolve baseline installation issue with broken pip package
- [ ] video saving implementation for `vpython` on native enviornments
- [x] Update Readme
